name: tp2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_settings_ui: ^3.0.1
  provider: ^6.0.5
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  intl: ^0.19.0
  settings_ui: ^2.0.2
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.2
  supabase_flutter: ^2.8.4
  bcrypt: ^1.1.3
  flutter_bcrypt: ^1.0.8
  url_launcher: ^6.3.1
  geocoding: ^3.0.0
  google_maps_flutter: ^2.12.1
  flutter_rating_bar: ^4.0.1

  # Pour la gestion d'images et la prise de photos
  image_picker: ^1.0.4  # Pour sélectionner des images depuis la galerie ou prendre des photos
  image_cropper: ^9.1.0  # Pour recadrer les images
  cached_network_image: ^3.3.0  # Pour afficher des images depuis le réseau avec cache
  file_picker: ^10.0.0  # Pour sélectionner plusieurs fichiers
  path_provider: ^2.1.1  # Pour accéder aux chemins de stockage
  path: ^1.8.3  # Pour manipuler les chemins de fichiers
  flutter_image_compress: ^2.4.0  # Pour compresser les images

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Ajoutez vos assets (images, fonts, etc.)
  assets:
    - assets/images/  # Dossier pour vos images locales
    - assets/icons/  # Dossier pour vos icônes

  # Configuration pour les fonts si nécessaire
  # fonts:
  #   - family: YourFontFamily
  #     fonts:
  #       - asset: fonts/YourFont-Regular.ttf
  #       - asset: fonts/YourFont-Bold.ttf
  #         weight: 700